name: Build Heatmap

on:
  schedule:
    - cron: "15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Heatmap CSV
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TEAM_NAME: ${{ secrets.TEAM_NAME }}
        run: |
          yarn
          node getWeeklyStreams.js > ./site/data.json

      - name: Commit New Data & Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

          cd $GITHUB_WORKSPACE

          git add site/data.json
          git commit -m "Updated heatmap dataset" || echo "No changes made"
          git push origin master

          cd site

          npx parcel-bundler build index.html --no-source-maps
          npx netlify-cli deploy --dir=dist --prod
